-- triggers and events
-- CREATING TRIGGER THAT AUTOMATICALLY INSERTS 
-- DATA INTO ANOTHER TABLE(YEHA CHAI EMPL0YEE_DEMOGRAPHICS) WHENEVER 
-- NEW ROW IS ADDED TO EMPLOYEE_SALARY

-- WHEN SALARY IS UPDATED ,WE WANT AUTOMATICALLLY UPDATES OTHER AS WELL


SELECT*
FROM employee_demographics;

SELECT*
FROM EMPLOYEE_SALARY;




DELIMITER $$
CREATE TRIGGER EMPLOYEE_INSERT
		AFTER INSERT ON EMPLOYEE_SALARY
        FOR EACH ROW
BEGIN
	INSERT INTO EMPLOYEE_DEMOGRAPHICS (EMPLOYEE_ID,FIRST_NAME,LAST_NAME)
    VALUES (NEW.EMPLOYEE_ID,NEW.FIRST_NAME,NEW.LAST_NAME);


END$$
DELIMITER ;

INSERT INTO EMPLOYEE_SALARY(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,occupation,salary,dept_id)
VALUES (13,'PRISHA','SHRESTHA','CEO',1000000,NULL);


-- EVENTS
-- IS SIMILAR TO TRIGGER,TRIGGER HAPPENS WHEN EVENT HAPPENS
-- IS  SCHEDULED TASK THAT RUNS AUTOMATICALLY  AT SPECIFIED TIME OR INTERVAL


SELECT*
FROM employee_demographics;


DELIMITER $$
CREATE EVENT delete_retriees
on schedule EVERY 30 SECOND
DO
BEGIN
	DELETE
    FROM EMPLOYEE_DEMOGRAPHICS
    WHERE AGE >=60;
END$$
DELIMITER ;


SHOW VARIABLES LIKE 'EVENT%';






